[tool.poetry]
name = "stanleyhub"
version = "0.1.0"
description = "Software Engineering & Cybersecurity Platform"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.1"
Flask-SQLAlchemy = "^2.5.1"
Werkzeug = "^2.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"